# Generated by Django 2.2.1 on 2019-06-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDrive', '0002_auto_20190618_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='upload_date',
        ),
    ]
