# Generated by Django 2.2.1 on 2019-06-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDrive', '0003_remove_upload_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
